name: Deploy website to server

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
      - node
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run build
      - run: node app.js &
