name: Deploy app to debian VPS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: node
    continue-on-error: true
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Set up repo on VPS
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        run: yarn install

      - name: Transpile TS project
        run: yarn run build

      - name: Check PM2 status
        run: pm2 status

      - name: Stop previus instance if active
      - run: if [ "$(pm2 id share-session)" != "[]" ]; then pm2 stop "share-session" && pm2 save --force; fi

      - name: Start old instance or create a new one
      - run: if [ "$(pm2 id share-session)" = "[]" ]; then pm2 start npm --name "share-session" -- run start && pm2 save --force; else pm2 start "share-session"; fi
