name: Deploy app to debian VPS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: node

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run build
      - run: |
          pm2 delete all
          pm2 start --name "share_session" -- run start
          pm2 save --force
