name: Deploy app to debian VPS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: node
    continue-on-error: true
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Set up repo on VPS
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        run: yarn install

      - name: Transpile TS project
        run: yarn run build

      - run: whoami
      - run: echo "$PWD"
      - run: pm2 status
      - run: pm2 id a
      - run: if [ "$(pm2 id share-session)" != "[]" ]; then pm2 stop "share-session" && pm2 save --force; fi
      # - name: Remove previous pm2 istance if exists
      #   run: if [ "$(pm2 id share-session)" != "[]" ]; then pm2 delete 0 && pm2 save --force; fi
      # - name: Start node instance with pm2
      - run: |
          pm2 start npm --name "share-session" -- run start
          pm2 save --force
